### ISSUE TITLE
Admin: MediaWiki login

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#1]
Administrators should be able to log into MediaWiki from anywhere in the Scripto interface.

One option is to provide a "login" link to a central login page on every Scripto page, which, after a successful login, redirects to the originating page with a "login successful" message. The "login" link would change to a "logout" link.

@kimisgold Is there a place we can add a "login" link on every page? Do you have other ideas?

**Comment by kimisgold** [comment]
Re: eb3de44: 
Chrome currently auto-populates the login form with my login credentials. As a result, whenever I navigated away from the page, the view would ask me if I wanted to abandon my changes to a form I might not have seen if I hadn't opened the login sidebar.

I recreated the sidebar as a persistent header bar so that the user can always see their logged-in status. That way they never miss the form, and it's a more familiar login design pattern.

We should probably allow users to leave the form unprompted, though.
