### ISSUE TITLE
Test typical workflow

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#28]
Here's what I see will be a typical workflow for a Scripto project, from installing the module to importing the project's content into Omeka. It glosses over many details, but following this guide should help you get acquainted with the interface. This will be a jumping-off point for discussion.

## 1. Project setup
From the administrative interface, an administrator will install the module, add a new project, then sync the project using the "Sync project" link. They will then add a link to the project to their site's navigation.

## 2. Transcription
From the public site, an end user will navigate to the project, select an item, select a media, then choose to edit the media. They will then enter a transcription of the media, mark it as complete, and save.

## 3. Project review
From the administrative interface, an administrator will select their project, filter items for "Is in progress," select an item that is in progress, filter media for "Is completed," and select a completed media. They will then review the revision for completeness. If it is indeed complete, they will mark the revision as approved and save.

## 4. Project import
From the administrative interface, an administrator will select their project then import the content using the "Import content" link. After the process is finished, they can see the imported content by navigating to the item that was completed and approved in the steps above.

**Comment by jdauteri** [comment]
I've gone through the testing a couple of times now, and haven't run into any major errors. I did notice a few minor issues that could be troublesome for some users:

1--When zooming out on an image (most noticeably in stacked view), the image sometimes disappears below the window panel so that you can no longer see nor drag it. I had to zoom back in, drag the image up in the window, and then zoom back out for it to remain in view. 

2--I liked the functionality in the old scripto that allowed you to adjust the size and positioning of the image while the cursor remained active in the text box. This still functions when moving the image around, but not when you use the zoom toolbar.

3--I started working with a document in stacked view, and adjusted the size of the text box to be larger. When I switched to side by side view, the text box filled the whole page, extending behind and beyond the image panel. I am able to adjust the box to fit back into the left side of the screen, but this might not be clear to some users. Can it automatically snap back into place when moving between views? Or maybe automatically appear big enough in stacked view for a user to not have to adjust the text box?

**Comment by jimsafley** [comment]
Thanks for the input. As I expected, the most evident issues are on the media edit page, specifically the interactions between the layout selector, media viewer, and text editor. @kim and I will look through each item and see what we can do to to make the experience better (I'm currently working on item 2).

**Comment by jdauteri** [comment]
I hope it was helpful. Would it also be possible to rotate the image within the media viewer?

**Comment by jimsafley** [comment]
There are rotation controls in the media viewer, but only if the media is a renderable image. Do you not see the rotation controls?
![rotation](https://user-images.githubusercontent.com/141955/41983519-53a8b2f0-79fc-11e8-9203-82b0fb433987.png)

**Comment by jimsafley** [comment]
@kimisgold I had to change `id="wikitext-editor-text"` to `class="wikitext-editor-text"` in the media edit page. This change broke the text editor control icons. Would you mind making the necessary changes to the CSS to fix them?

**Comment by jimsafley** [comment]
@jdauteri I made changes that should fix <span>#</span>2. Please confirm that the cursor remains in the textarea while interacting with the viewer controls, and while switching between layouts and full screen.

I'll work on <span>#</span>1, but know that you can click the "Reset" button if you ever lose sight of the image.

@kim Would you mind investigating <span>#</span>3? I believe we saw a similar issue on the vertical view while demonstrating the interface during our last meeting.

**Comment by jdauteri** [comment]
@jimsafley The cursor still isn't remaining in the text area on my end, neither for switching the layouts or for interacting with the viewer. The text toolbar also appears strange now--I've attached an image. 
![screen shot 2018-06-27 at 2 32 48 pm](https://user-images.githubusercontent.com/25283961/41992661-1f616eb8-7a17-11e8-93c0-26fe0e6478d9.png)

**Comment by jimsafley** [comment]
Yes, we're currently working on fixing the text editor toolbar. Strange that the cursor position isn't being preserved. Try hard reloading your browser in case the old scripts are being cached.

**Comment by jdauteri** [comment]
A hard reload did it. The cursor stays in place in both instances now.

**Comment by kimisgold** [comment]
Wikitext buttons and issues with the vertical layout should be fixed.

**Comment by mebrett** [comment]
Where did we decide to put the protection/stop editing functionality? I can see the information that a media is open to edits, but I can't find where to prevent future edits, either on media or item view.

**Comment by jimsafley** [comment]
Once you're logged into Scripto, the "Edit protection" controls should appear under the "Review status" controls.

**Comment by mebrett** [comment]
I'm only seeing completion and approval: 
![screen shot 2018-06-29 at 10 28 40 am](https://user-images.githubusercontent.com/2314070/42097871-3fc0243a-7b87-11e8-8021-4835fed51681.png)

**Comment by mebrett** [comment]
Functionality is great. I have some thoughts on interface tweaks, mostly to do with clarity of language and buttons.

The main thing - and I'm curious to hear from Jessica on this as well - is the language for the admin-side actions "sync" and "import". Because we're *in* Scripto when we take these actions, I think "export" or "send data to Omeka" makes more sense than "Import", which has the connotation of bringing in data (to Scripto) rather than pushing it out (to Omeka)

**Comment by jimsafley** [comment]
I've struggled with "import" and "sync" since the beginning of the project, but haven't come up with better terminology.

The "import/export" question is difficult because it all depends on your perspective: you don't like "import" because we're initiating the action from within Scripto; I don't like "export" because Scripto exists in Omeka and the transcriptions exist in MediaWiki. If we are to change the name, I suggest we avoid import/export all together.

As for "sync," I'm just not sure how else we'd describe the synchronization of the Omeka item set with the Scripto project.

**Comment by mebrett** [comment]
My only hangup with sync is that some people will think it does both things at once - brings in data from Omeka and sends data back at the same time. 

I agree with you on export/import - I'll try and brainstorm some alternate language which is both clear and concise.
