### ISSUE TITLE
Explain Scripto/Mediawiki user account creation.

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#35]
Testers were confused by having to verify their new Scripto accounts on Mediawiki. On the account creation form, there should be some orientation copy that includes the Scripto relationship to Mediawiki.

**Comment by mebrett** [comment]
Workshopping some text:

"Thank you for your interest in (Project).* Use this form to create an account for our MediaWiki, which helps power our crowdsourcing** platform. When you verify your account, it will take you to the MediaWiki main page; once you are done there, come back to this site to get started."

*If we can put this somewhere people can customize it, otherwise cut this sentence.
** This was originally "transcription" but since some projects may be translation, I changed it.

@sharonmleon @jdauteri  thoughts?

**Comment by jdauteri** [comment]
This sounds great. I would only add a bit to the "once you are done there" section--should we be more explicit about users need to "do there?" The part about it powering the project is useful info, but it still is unclear why the user is taken to that page rather than where they need to be to start transcribing/translating. I think we should either be more explicit about why the user is taken to the mediawiki page, or maybe change it to something like "you don't need to do anything on that page, just return to this site to get started." 

I'm going to start drafting documentation for the sign up process soon so I'll let you know if anything else occurs to me while I'm working through that.

**Comment by mebrett** [comment]
You make a good point. Is there anything the user needs to do on that page? Or is more a matter of clicking the link? 

If it's just a matter of clicking the link, we could say "When you verify your account, it will take you to the MediaWiki main page; once the page has loaded your account has been verified and you can close the window. You will not need to take any action on the MediaWiki view, everything happens on our main page."

**Comment by jdauteri** [comment]
No further action is needed once the user arrives at the MediaWiki, and this is the only time they need to visit this page. I tweaked the copy just a bit - what do you think? : "When you click the link in your email to verify your account, it will take you to the MediaWiki main page; once the page has loaded your account has been verified and you can close the window. This is the only time you'll need to visit the MediaWiki page*; everything else will be done through our main page*."

*should we change page to site?
