### ISSUE TITLE
Examine useful tools in Scripto's text editor

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#50]
A tester observed that the hidden comment and heading formatting tools in Scripto's text editors don't seem to be necessary. I disagree on the headings, but instead question when a transcriber/translator would need the "Preformatted" formatting and agree regarding hidden comments. Reviewing what's actually necessary could save some vertical space in that editor's toolbar.

**Comment by jdauteri** [comment]
My take on the text editor is that a lot of these options could probably be removed/replaced. I agree that "Preformatted" and hidden comments are not necessary, nor do I see the need for a horizontal rule option. I also tend to agree with the tester (that might have been my comment?) that headings aren't very useful--in the 150 or so documents I worked through last summer, I don't remembering needing this kind of formatting (although I see how other kinds of projects might find it useful to have). Maybe a compromise would be to lessen the amount of options available (for instance, keep h1-h3 and get rid of h4-h5) to save space?

If it's possible to make any additions, I think a superscript and a table-making tool would be useful. Again, I understand this needs to be applicable across all Scripto projects, but I think superscript is commonly used for dates and abbreviations. This is maybe less true for tables, although it seemed that a lot of PWD transcribers weren't quite sure what to do with media that included some kind of table and would leave these items half-finished, so that's why I'm mentioning it here. 

Will we be including a formatting/HTML tips section like we did in the previous PWD version? It was very helpful to have available on the transcription view while working through each document. Depending on how many tool options we include in the editor (or not), this could be a place to show users how to format/when to use options like headings, superscript, tables, line breaks, etc.

**Comment by mebrett** [comment]
I agree that Preformatted and hidden comments are not needed. 

For PWD we don't really need the headers. I can see there being other projects that do. My concern with them is how does the formatting of headers within the transcription/translation interact with heading levels in the page as a whole? Will that mess up accessibility/legibility?

For 18th/19th century documents, superscript would be amazing. 

I think we should include a formatting section as @jdauteri mentions - we can pull from the old one with some modifications.

**Comment by jimsafley** [comment]
This reminds me that the currently provided tools are just the basic MediaWiki set that come with the [LML editor](https://github.com/jimsafley/LmlEditor) used by Scripto. MediaWiki has many [formatting options](https://www.mediawiki.org/wiki/Help:Formatting), including some HTML tags like `<sup>` and `<sub>`, that I could add to the text editor. I could even add a template for adding tables if that's what we need.

@mebrett You should assemble a comprehensive list of formatting tools that the text editor needs for a majority of our users. We can explain any further formatting options in documentation.

**Comment by mebrett** [comment]
@jimsafley PWD users or Scripto users?

**Comment by jimsafley** [comment]
Scripto

**Comment by kimisgold** [comment]
Just a note as I work on the discussion vs media/show views: if available, the discussion views could use a few unique functions, namely the abilities to insert a user link and to create a timestamp.

**Comment by mebrett** [comment]
An easy timestamp would be super useful

**Comment by mebrett** [comment]
Formatting needs for Scripto projects:
- Bold
- Italic
- Underline
- Headings (I'm concerned about this clashing with the formatting of the pages and thereby impacting accessibility)
- Horizontal rule
- bullet list
- numbered list
- blockquote
- strike through

Tables would be nice, but I suspect that implementing them might prove awkward. 

In the documentation for Scripto, we should link to the list of [HTML entities for special characters](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references), so that projects can include that in their guidelines as necessary. 

For talk pages, it would be useful to have:
- Bold
- Italic
- Underline
- Blockquote
- timestamp
- signature

**Comment by jdauteri** [comment]
I think these changes are very useful. I still wonder if including Headings 1-5 is necessary; would it make sense to just include tools for 1-3 and explain how to format more headings in the Transcription Guidelines? Also, would a superscript option be too specific to include across all Scripto projects?
