### ISSUE TITLE
Clear completed documents from project

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Scripto#61]
Add a setting to remove approved and imported documents from the project

**Comment by jimsafley** [comment]
We can't remove approved+imported items from the project because synching would bring them back anyway. Instead, the [filter-approved branch](https://github.com/omeka-s-modules/Scripto/tree/filter-approved) introduces a project-level "Filter approved" setting that filters out approved items from the public browse view. Give it a try.

**Comment by jdauteri** [comment]
I just tested this setting out on dev.omeka.org/omeka-s, and think it's a great solution.

**Comment by mebrett** [comment]
Agreed - hiding the approved options is very helpful.
