### ISSUE TITLE
Adding Context/Orientation for New Scripto Users

### ISSUE THREAD

**Issue by jdauteri** [omeka-s-modules/Scripto#63]
Incorporate text to explain transcription accounts to new users, potentially on sign-up page or on home page.

Copy from the old sign-up page [https://web.archive.org/web/20170630110029/http://wardepartmentpapers.org/transcribe.php]:
The Papers of the War Department Project is enlisting the help of our community of users to transcribe the documents in the archive. With over 45,000 documents and hundreds of thousands of individual pages, we have a monumental task ahead of us. Nonetheless, the digital archive provides us with a unique opportunity to capitalize on the energy and enthusiasm of users to improve the archive for everyone. By working to transcribe individual archival pages, contributors will help us improve all users’ ability to locate the documents they need by providing text essential to the website’s search engine. Additionally, the project editors will gain an important insight into the topics and issues from the collection that are especially interesting to the community. Finally, Transcription Associates have the opportunity to learn about the history of the War Department in the first decades of the new nation, and to contribute to preserving and presenting that history for the public.

**Comment by jimsafley** [comment]
It seems to me the natural place for this is in the project guidelines. What do you think @kimisgold?

**Comment by mebrett** [comment]
Rather than the language above, it would be helpful to have *on the sign-up page* a short block of text (configurable) which explains what the user is signing up for. Something like "Use the form below to sign up as a transcriber for this project."

Having that distinction will be useful for sites which are using Scripto and Contribution, or otherwise have people who are signing up for some other sort of access.
