### ISSUE TITLE
Is there a reason why the url starts with "scripto" before the site "s/my-site"?

### ISSUE THREAD

**Issue by Daniel-KM** [omeka-s-modules/Scripto#70]
Is there a reason why the url starts with "scripto" before the site "s/my-site", so it is not compliant with any other module and theming mechanism?
So why `https://example.org/scripto/s/my-site/1/1/1/media` and not `https://example.org/s/my-site/scripto/1/1/1/media`?

**Comment by jimsafley** [comment]
We developed Scripto's public interface to be a self-contained application in the top-level namespace `/scripto/`, for one because it _is_ a separate application and, more to point, because its structural and styling requirements are so particular. We initially made no accommodations for sites - users would navigate to the Scripto application from a site and encounter a jarring styling difference. Our solution was to add a way for site administrators to include a theme-specific stylesheet to Scripto's assets, which Scripto automatically detects and loads.

**Comment by Daniel-KM** [comment]
So if it is a separate application, is it possible to separate Scripto and the Omeka module? So any other people can create a similar Wordpress module. Or in the other way, you can create a core Scripto then a Scripto module for Omeka or a Scripto module for Drupal. It may be clearer.

Anyway, I checked the inverted route (Scripto inside site) and there is probably not a lot of work to do to make it working as a standard module. The main point is to manage the theme templates outside of the module, in the views of the theme and to have a route dedicated to an Omeka site, not to an application.

**Comment by jimsafley** [comment]
Scripto is exclusive to Omeka S. It's a separate application in the sense that it has a separate login and needs uniform design across all sites. We've already accommodated theme writers who want to make the transition from the site to the Scripto application less jarring, and we have no plans to invert the route.

**Comment by Daniel-KM** [comment]
>  it has a separate login 

I'll integrate it with the module [Guest](https://github.com/daniel-km/Omeka-S-module-Guest) (later) for a better end user experience.

> and needs uniform design across all sites.

Some multi-sites installs need a fully customizable design through theme templates.

> no plans to invert the route

I'll write a new config file for that, so it will allow to let the admin choose.
